version: '3.8'

services:
  # Servicio principal de la aplicación web
  funds-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funds-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - funds-network

  # Servicio de desarrollo (opcional)
  funds-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: funds-frontend-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - funds-network

networks:
  funds-network:
    driver: bridge

volumes:
  node_modules:
